### ISSUE TITLE
Cookie Blob

### ISSUE THREAD

**Issue by gideongrinberg** [jakehadar/fresh-direct-poller#1]
Hi, @jakehadar,
I was trying to make what you made, and I failed miserably. In trying to use your python script, I noticed I need a "COOKIE_BLOB." Your readme doesn't say how to find that. Could you please tell me how to find it? 

Thanks in advance.

**Comment by jakehadar** [comment]
Thanks for raising the issue @Gideon357 ! I'm pulling an update into master now where COOKIE_BLOB is no longer needed.
